version: "3.9"
services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5010:5000"
      - "5011:5001"
      - "5012:5002"

    volumes:
      - ./mlruns:/home/mlflow/mlruns
      - ./mlartifacts:/home/mlflow/mlartifacts

